/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExtendedMessageOpenEventInformation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MessageOpenSearchResponse
 */
public class MessageOpenSearchResponseTest {
    private final MessageOpenSearchResponse model = new MessageOpenSearchResponse();

    /**
     * Model tests for MessageOpenSearchResponse
     */
    @Test
    public void testMessageOpenSearchResponse() {
        // TODO: test MessageOpenSearchResponse
    }

    /**
     * Test the property 'opens'
     */
    @Test
    public void opensTest() {
        // TODO: test opens
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

}
