/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SentCountsResponseDaysInner
 */
public class SentCountsResponseDaysInnerTest {
    private final SentCountsResponseDaysInner model = new SentCountsResponseDaysInner();

    /**
     * Model tests for SentCountsResponseDaysInner
     */
    @Test
    public void testSentCountsResponseDaysInner() {
        // TODO: test SentCountsResponseDaysInner
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'sent'
     */
    @Test
    public void sentTest() {
        // TODO: test sent
    }

}
