/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateValidationResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TemplateValidationResponse
 */
public class TemplateValidationResponseTest {
    private final TemplateValidationResponse model = new TemplateValidationResponse();

    /**
     * Model tests for TemplateValidationResponse
     */
    @Test
    public void testTemplateValidationResponse() {
        // TODO: test TemplateValidationResponse
    }

    /**
     * Test the property 'allContentIsValid'
     */
    @Test
    public void allContentIsValidTest() {
        // TODO: test allContentIsValid
    }

    /**
     * Test the property 'htmlBody'
     */
    @Test
    public void htmlBodyTest() {
        // TODO: test htmlBody
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'suggestedTemplateModel'
     */
    @Test
    public void suggestedTemplateModelTest() {
        // TODO: test suggestedTemplateModel
    }

    /**
     * Test the property 'textBody'
     */
    @Test
    public void textBodyTest() {
        // TODO: test textBody
    }

}
