/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * MessageEventDetailsDetails
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class MessageEventDetailsDetails {
  public static final String SERIALIZED_NAME_BOUNCE_I_D = "BounceID";
  @SerializedName(SERIALIZED_NAME_BOUNCE_I_D)
  private String bounceID;

  public static final String SERIALIZED_NAME_DELIVERY_MESSAGE = "DeliveryMessage";
  @SerializedName(SERIALIZED_NAME_DELIVERY_MESSAGE)
  private String deliveryMessage;

  public static final String SERIALIZED_NAME_DESTINATION_I_P = "DestinationIP";
  @SerializedName(SERIALIZED_NAME_DESTINATION_I_P)
  private String destinationIP;

  public static final String SERIALIZED_NAME_DESTINATION_SERVER = "DestinationServer";
  @SerializedName(SERIALIZED_NAME_DESTINATION_SERVER)
  private String destinationServer;

  public static final String SERIALIZED_NAME_SUMMARY = "Summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  private String summary;

  public MessageEventDetailsDetails() {
  }

  public MessageEventDetailsDetails bounceID(String bounceID) {
    
    
    
    
    this.bounceID = bounceID;
    return this;
  }

   /**
   * Get bounceID
   * @return bounceID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBounceID() {
    return bounceID;
  }


  public void setBounceID(String bounceID) {
    
    
    
    this.bounceID = bounceID;
  }


  public MessageEventDetailsDetails deliveryMessage(String deliveryMessage) {
    
    
    
    
    this.deliveryMessage = deliveryMessage;
    return this;
  }

   /**
   * Get deliveryMessage
   * @return deliveryMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDeliveryMessage() {
    return deliveryMessage;
  }


  public void setDeliveryMessage(String deliveryMessage) {
    
    
    
    this.deliveryMessage = deliveryMessage;
  }


  public MessageEventDetailsDetails destinationIP(String destinationIP) {
    
    
    
    
    this.destinationIP = destinationIP;
    return this;
  }

   /**
   * Get destinationIP
   * @return destinationIP
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDestinationIP() {
    return destinationIP;
  }


  public void setDestinationIP(String destinationIP) {
    
    
    
    this.destinationIP = destinationIP;
  }


  public MessageEventDetailsDetails destinationServer(String destinationServer) {
    
    
    
    
    this.destinationServer = destinationServer;
    return this;
  }

   /**
   * Get destinationServer
   * @return destinationServer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDestinationServer() {
    return destinationServer;
  }


  public void setDestinationServer(String destinationServer) {
    
    
    
    this.destinationServer = destinationServer;
  }


  public MessageEventDetailsDetails summary(String summary) {
    
    
    
    
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSummary() {
    return summary;
  }


  public void setSummary(String summary) {
    
    
    
    this.summary = summary;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MessageEventDetailsDetails instance itself
   */
  public MessageEventDetailsDetails putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageEventDetailsDetails messageEventDetailsDetails = (MessageEventDetailsDetails) o;
    return Objects.equals(this.bounceID, messageEventDetailsDetails.bounceID) &&
        Objects.equals(this.deliveryMessage, messageEventDetailsDetails.deliveryMessage) &&
        Objects.equals(this.destinationIP, messageEventDetailsDetails.destinationIP) &&
        Objects.equals(this.destinationServer, messageEventDetailsDetails.destinationServer) &&
        Objects.equals(this.summary, messageEventDetailsDetails.summary)&&
        Objects.equals(this.additionalProperties, messageEventDetailsDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bounceID, deliveryMessage, destinationIP, destinationServer, summary, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageEventDetailsDetails {\n");
    sb.append("    bounceID: ").append(toIndentedString(bounceID)).append("\n");
    sb.append("    deliveryMessage: ").append(toIndentedString(deliveryMessage)).append("\n");
    sb.append("    destinationIP: ").append(toIndentedString(destinationIP)).append("\n");
    sb.append("    destinationServer: ").append(toIndentedString(destinationServer)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("BounceID");
    openapiFields.add("DeliveryMessage");
    openapiFields.add("DestinationIP");
    openapiFields.add("DestinationServer");
    openapiFields.add("Summary");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MessageEventDetailsDetails
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!MessageEventDetailsDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MessageEventDetailsDetails is not found in the empty JSON string", MessageEventDetailsDetails.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("BounceID") != null && !jsonObj.get("BounceID").isJsonNull()) && !jsonObj.get("BounceID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `BounceID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("BounceID").toString()));
      }
      if ((jsonObj.get("DeliveryMessage") != null && !jsonObj.get("DeliveryMessage").isJsonNull()) && !jsonObj.get("DeliveryMessage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DeliveryMessage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DeliveryMessage").toString()));
      }
      if ((jsonObj.get("DestinationIP") != null && !jsonObj.get("DestinationIP").isJsonNull()) && !jsonObj.get("DestinationIP").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DestinationIP` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DestinationIP").toString()));
      }
      if ((jsonObj.get("DestinationServer") != null && !jsonObj.get("DestinationServer").isJsonNull()) && !jsonObj.get("DestinationServer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DestinationServer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DestinationServer").toString()));
      }
      if ((jsonObj.get("Summary") != null && !jsonObj.get("Summary").isJsonNull()) && !jsonObj.get("Summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Summary").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MessageEventDetailsDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MessageEventDetailsDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MessageEventDetailsDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MessageEventDetailsDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<MessageEventDetailsDetails>() {
           @Override
           public void write(JsonWriter out, MessageEventDetailsDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public MessageEventDetailsDetails read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             MessageEventDetailsDetails instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MessageEventDetailsDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MessageEventDetailsDetails
  * @throws IOException if the JSON string is invalid with respect to MessageEventDetailsDetails
  */
  public static MessageEventDetailsDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MessageEventDetailsDetails.class);
  }

 /**
  * Convert an instance of MessageEventDetailsDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

