/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateValidationResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TemplateValidationResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TemplateValidationResponse {
  public static final String SERIALIZED_NAME_ALL_CONTENT_IS_VALID = "AllContentIsValid";
  @SerializedName(SERIALIZED_NAME_ALL_CONTENT_IS_VALID)
  private Boolean allContentIsValid;

  public static final String SERIALIZED_NAME_HTML_BODY = "HtmlBody";
  @SerializedName(SERIALIZED_NAME_HTML_BODY)
  private TemplateValidationResult htmlBody;

  public static final String SERIALIZED_NAME_SUBJECT = "Subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private TemplateValidationResult subject;

  public static final String SERIALIZED_NAME_SUGGESTED_TEMPLATE_MODEL = "SuggestedTemplateModel";
  @SerializedName(SERIALIZED_NAME_SUGGESTED_TEMPLATE_MODEL)
  private Object suggestedTemplateModel;

  public static final String SERIALIZED_NAME_TEXT_BODY = "TextBody";
  @SerializedName(SERIALIZED_NAME_TEXT_BODY)
  private TemplateValidationResult textBody;

  public TemplateValidationResponse() {
  }

  public TemplateValidationResponse allContentIsValid(Boolean allContentIsValid) {
    
    
    
    
    this.allContentIsValid = allContentIsValid;
    return this;
  }

   /**
   * Get allContentIsValid
   * @return allContentIsValid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAllContentIsValid() {
    return allContentIsValid;
  }


  public void setAllContentIsValid(Boolean allContentIsValid) {
    
    
    
    this.allContentIsValid = allContentIsValid;
  }


  public TemplateValidationResponse htmlBody(TemplateValidationResult htmlBody) {
    
    
    
    
    this.htmlBody = htmlBody;
    return this;
  }

   /**
   * Get htmlBody
   * @return htmlBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateValidationResult getHtmlBody() {
    return htmlBody;
  }


  public void setHtmlBody(TemplateValidationResult htmlBody) {
    
    
    
    this.htmlBody = htmlBody;
  }


  public TemplateValidationResponse subject(TemplateValidationResult subject) {
    
    
    
    
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateValidationResult getSubject() {
    return subject;
  }


  public void setSubject(TemplateValidationResult subject) {
    
    
    
    this.subject = subject;
  }


  public TemplateValidationResponse suggestedTemplateModel(Object suggestedTemplateModel) {
    
    
    
    
    this.suggestedTemplateModel = suggestedTemplateModel;
    return this;
  }

   /**
   * Get suggestedTemplateModel
   * @return suggestedTemplateModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getSuggestedTemplateModel() {
    return suggestedTemplateModel;
  }


  public void setSuggestedTemplateModel(Object suggestedTemplateModel) {
    
    
    
    this.suggestedTemplateModel = suggestedTemplateModel;
  }


  public TemplateValidationResponse textBody(TemplateValidationResult textBody) {
    
    
    
    
    this.textBody = textBody;
    return this;
  }

   /**
   * Get textBody
   * @return textBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateValidationResult getTextBody() {
    return textBody;
  }


  public void setTextBody(TemplateValidationResult textBody) {
    
    
    
    this.textBody = textBody;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TemplateValidationResponse instance itself
   */
  public TemplateValidationResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateValidationResponse templateValidationResponse = (TemplateValidationResponse) o;
    return Objects.equals(this.allContentIsValid, templateValidationResponse.allContentIsValid) &&
        Objects.equals(this.htmlBody, templateValidationResponse.htmlBody) &&
        Objects.equals(this.subject, templateValidationResponse.subject) &&
        Objects.equals(this.suggestedTemplateModel, templateValidationResponse.suggestedTemplateModel) &&
        Objects.equals(this.textBody, templateValidationResponse.textBody)&&
        Objects.equals(this.additionalProperties, templateValidationResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allContentIsValid, htmlBody, subject, suggestedTemplateModel, textBody, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateValidationResponse {\n");
    sb.append("    allContentIsValid: ").append(toIndentedString(allContentIsValid)).append("\n");
    sb.append("    htmlBody: ").append(toIndentedString(htmlBody)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    suggestedTemplateModel: ").append(toIndentedString(suggestedTemplateModel)).append("\n");
    sb.append("    textBody: ").append(toIndentedString(textBody)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AllContentIsValid");
    openapiFields.add("HtmlBody");
    openapiFields.add("Subject");
    openapiFields.add("SuggestedTemplateModel");
    openapiFields.add("TextBody");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TemplateValidationResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TemplateValidationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateValidationResponse is not found in the empty JSON string", TemplateValidationResponse.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `HtmlBody`
      if (jsonObj.get("HtmlBody") != null && !jsonObj.get("HtmlBody").isJsonNull()) {
        TemplateValidationResult.validateJsonObject(jsonObj.getAsJsonObject("HtmlBody"));
      }
      // validate the optional field `Subject`
      if (jsonObj.get("Subject") != null && !jsonObj.get("Subject").isJsonNull()) {
        TemplateValidationResult.validateJsonObject(jsonObj.getAsJsonObject("Subject"));
      }
      // validate the optional field `TextBody`
      if (jsonObj.get("TextBody") != null && !jsonObj.get("TextBody").isJsonNull()) {
        TemplateValidationResult.validateJsonObject(jsonObj.getAsJsonObject("TextBody"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateValidationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateValidationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateValidationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateValidationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateValidationResponse>() {
           @Override
           public void write(JsonWriter out, TemplateValidationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateValidationResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TemplateValidationResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateValidationResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateValidationResponse
  * @throws IOException if the JSON string is invalid with respect to TemplateValidationResponse
  */
  public static TemplateValidationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateValidationResponse.class);
  }

 /**
  * Convert an instance of TemplateValidationResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

