/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BounceSearchResponse;
import com.konfigthis.client.model.DeliveryStatsResponse;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BouncesApiApi
 */
@Disabled
public class BouncesApiApiTest {

    private static BouncesApiApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BouncesApiApi(apiClient);
    }

    /**
     * Activate a bounce
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void activateBounceTest() throws ApiException {
        Long bounceid = null;
        Object response = api.activateBounce(bounceid)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a single bounce
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBounceTest() throws ApiException {
        Long bounceid = null;
        Object response = api.getBounce(bounceid)
                .execute();
        // TODO: test validations
    }

    /**
     * Get delivery stats
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDeliveryStatsTest() throws ApiException {
        DeliveryStatsResponse response = api.getDeliveryStats()
                .execute();
        // TODO: test validations
    }

    /**
     * Get bounce dump
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDumpTest() throws ApiException {
        Long bounceid = null;
        Object response = api.getDump(bounceid)
                .execute();
        // TODO: test validations
    }

    /**
     * Get bounces
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listBouncesTest() throws ApiException {
        Integer count = null;
        Integer offset = null;
        String type = null;
        Boolean inactive = null;
        String emailFilter = null;
        String messageID = null;
        String tag = null;
        LocalDate todate = null;
        LocalDate fromdate = null;
        BounceSearchResponse response = api.listBounces(count, offset)
                .type(type)
                .inactive(inactive)
                .emailFilter(emailFilter)
                .messageID(messageID)
                .tag(tag)
                .todate(todate)
                .fromdate(fromdate)
                .execute();
        // TODO: test validations
    }

}
