/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.EditServerConfigurationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServerConfigurationApiApi
 */
@Disabled
public class ServerConfigurationApiApiTest {

    private static ServerConfigurationApiApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ServerConfigurationApiApi(apiClient);
    }

    /**
     * Get Server Configuration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConfigurationTest() throws ApiException {
        Object response = api.getConfiguration()
                .execute();
        // TODO: test validations
    }

    /**
     * Edit Server Configuration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateConfigurationTest() throws ApiException {
        String bounceHookUrl = null;
        String clickHookUrl = null;
        String color = null;
        String deliveryHookUrl = null;
        String inboundDomain = null;
        String inboundHookUrl = null;
        Integer inboundSpamThreshold = null;
        String name = null;
        String openHookUrl = null;
        Boolean postFirstOpenOnly = null;
        Boolean rawEmailEnabled = null;
        Boolean smtpApiActivated = null;
        String trackLinks = null;
        Boolean trackOpens = null;
        Object response = api.updateConfiguration()
                .bounceHookUrl(bounceHookUrl)
                .clickHookUrl(clickHookUrl)
                .color(color)
                .deliveryHookUrl(deliveryHookUrl)
                .inboundDomain(inboundDomain)
                .inboundHookUrl(inboundHookUrl)
                .inboundSpamThreshold(inboundSpamThreshold)
                .name(name)
                .openHookUrl(openHookUrl)
                .postFirstOpenOnly(postFirstOpenOnly)
                .rawEmailEnabled(rawEmailEnabled)
                .smtpApiActivated(smtpApiActivated)
                .trackLinks(trackLinks)
                .trackOpens(trackOpens)
                .execute();
        // TODO: test validations
    }

}
