/*
 * Postmark API
 * Postmark makes sending and receiving email incredibly easy. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Attachment;
import com.konfigthis.client.model.CreateTemplateRequest;
import com.konfigthis.client.model.EditTemplateRequest;
import com.konfigthis.client.model.EmailWithTemplateRequest;
import com.konfigthis.client.model.MessageHeader;
import com.konfigthis.client.model.SendEmailResponse;
import com.konfigthis.client.model.SendEmailTemplatedBatchRequest;
import com.konfigthis.client.model.TemplateValidationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TemplatesApiApi
 */
@Disabled
public class TemplatesApiApiTest {

    private static TemplatesApiApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TemplatesApiApi(apiClient);
    }

    /**
     * Create a Template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTemplateTest() throws ApiException {
        String name = null;
        String subject = null;
        String alias = null;
        String htmlBody = null;
        String textBody = null;
        Object response = api.createTemplate(name, subject)
                .alias(alias)
                .htmlBody(htmlBody)
                .textBody(textBody)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete a Template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTemplateTest() throws ApiException {
        String templateIdOrAlias = null;
        Object response = api.deleteTemplate(templateIdOrAlias)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a Template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTemplateByIdTest() throws ApiException {
        String templateIdOrAlias = null;
        Object response = api.getTemplateById(templateIdOrAlias)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the Templates associated with this Server
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTemplatesTest() throws ApiException {
        Double count = null;
        Double offset = null;
        Object response = api.listTemplates(count, offset)
                .execute();
        // TODO: test validations
    }

    /**
     * Send a batch of email using templates.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendBatchWithTemplatesTest() throws ApiException {
        List<EmailWithTemplateRequest> messages = null;
        List<SendEmailResponse> response = api.sendBatchWithTemplates()
                .messages(messages)
                .execute();
        // TODO: test validations
    }

    /**
     * Send an email using a Template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendEmailTemplateTest() throws ApiException {
        String from = null;
        String templateAlias = null;
        Integer templateId = null;
        Object templateModel = null;
        String to = null;
        List<Attachment> attachments = null;
        String bcc = null;
        String cc = null;
        List<MessageHeader> headers = null;
        Boolean inlineCss = null;
        String replyTo = null;
        String tag = null;
        String trackLinks = null;
        Boolean trackOpens = null;
        SendEmailResponse response = api.sendEmailTemplate(from, templateAlias, templateId, templateModel, to)
                .attachments(attachments)
                .bcc(bcc)
                .cc(cc)
                .headers(headers)
                .inlineCss(inlineCss)
                .replyTo(replyTo)
                .tag(tag)
                .trackLinks(trackLinks)
                .trackOpens(trackOpens)
                .execute();
        // TODO: test validations
    }

    /**
     * Update a Template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTemplateTest() throws ApiException {
        String templateIdOrAlias = null;
        String alias = null;
        String htmlBody = null;
        String name = null;
        String subject = null;
        String textBody = null;
        Object response = api.updateTemplate(templateIdOrAlias)
                .alias(alias)
                .htmlBody(htmlBody)
                .name(name)
                .subject(subject)
                .textBody(textBody)
                .execute();
        // TODO: test validations
    }

    /**
     * Test Template Content
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validateTemplateContentTest() throws ApiException {
        String htmlBody = null;
        Boolean inlineCssForHtmlTestRender = null;
        String subject = null;
        Object testRenderModel = null;
        String textBody = null;
        Object response = api.validateTemplateContent()
                .htmlBody(htmlBody)
                .inlineCssForHtmlTestRender(inlineCssForHtmlTestRender)
                .subject(subject)
                .testRenderModel(testRenderModel)
                .textBody(textBody)
                .execute();
        // TODO: test validations
    }

}
